### ISSUE TITLE
Work out the features of the game

### ISSUE THREAD

**Issue by valentingavran** [SS20-SE2-Monopoly-Team/monopoly#1]
On April 1st there will be a meeting with Prof. Macho where we present our game idea and its features.

- [x] Inform yourself about the rules of Monopoly
- [x] Write a comment under this issue, which contains your ideas (only if it is something not yet said)
- [x] Compose one A4 page containing the required content
- [x] Send the document to the professor via email until noon on April 1st

**Comment by valentingavran** [comment]
Das Spiel soll meiner Meinung nach auf den Grundregeln basieren. Jemanden Geld leihen, Kredite usw. (Siehe [Nichtoffizielle Varianten der Spielregeln](https://de.wikipedia.org/wiki/Monopoly#Nichtoffizielle_Varianten_der_Spielregeln)) sollen zunächst nicht implementiert werden

**Lobby**
- GPS verwenden beim Erstellen eines neuen Spiels um das Monopoly Spielbrett mit der jeweiligen Länderversion (zunächst Österreich?, Deutschland?, USA?) zu generieren. Benutzer, welche einem Spiel beitreten, verwenden die Version, mit der das Spielbrett erstellt wurde. Eventuell den Standort nur zum Vorschlagen von Versionen oder Sprachen verwenden
- beim Erstellen eines Spiels kann man außerdem das Startkapital eintragen
- dynamische Links (welche man über WhatsApp usw. teilen kann) um einer Lobby beizutreten oder Lobby ID eingeben bzw. Freunde direkt einladen

**Ingame Funktionen**
- während man nicht dran ist, kann man das Gerät schütteln um zusätzlich ein wenig Geld zu erlangen (Schummelfunktion)
- während man dran ist, muss man das Gerät schütteln um zu würfeln

**Sonstiges:**
- UI Sprache ändert sich je nach Spracheinstellungen des Geräts (Sprache des Spielbretts jedoch unabhängig und diese kommt auf die eingestellte Version in der Lobby an)
- Rangliste (Freunde/Landesweit/Weltweit)
- Freundesliste (zum Späteren einladen von Spielern in der Lobby)
- Hinzufügen und entfernen von Freunden
- Aufgeben
- Rundenzeiten begrenzen
- Matchsuche


Sieht eventuell viel aus aber wir sind immerhin zu sechst  👨🏻‍💻

**Comment by dermutzh** [comment]
Schummelfunktionsidee:
Wenn man im Gefängnis ist, kann der Schummelbutton geklickt werden. Daraufhin wird automatisch gewürfelt und das Endresultat ist immer 2 Mal eine 6. Wenn ein Gegenspieler vermutet, dass geschummelt wurde kann dieser das mit einem Button anfechten. 
Wenn geschummelt wurde, muss der „Cheater“ wieder ins Gefängnis zurück und Strafe zahlen. Der Spieler der das hingegen aufgedeckt hat, bekommt X Geld aufs Konto gutgeschrieben.

**Comment by Jesse2518** [comment]
Idee:
Befindet sich ein Spieler auf einem gegnerischen Feld, könnte man durch Schütteln ein Haus zum Einsturz bringen. Kann auch gemacht werden, wenn man nicht am Zug ist. Findet der Inhaber das in der selben Runde heraus, kann er ein Haus des Cheaters frei positionieren. 
High risk, high reward.

**Comment by SgtGraf** [comment]
Idee für Schummelfunktion:

Häuser platzieren die man nicht gekauft hat.
Spieler A platziert ein Haus ohne es zu kaufen.
Kann von Spieler B durch eine Zahlung an die Bank "überprüft" werden.
Bestätigt sich der Verdacht, muss A eine Strafe an B zahlen und B bekommt sein Geld zurück.

Hat spieler A jedoch nicht geschummelt, bleibt das Geld von B bei der Bank. Damit wird verhindert, dass jede Runde das "Aufdecken" verwendet wird.

**Comment by bferijan** [comment]
Grundlegendes: 
Netzwerk aufbauen (c.a. 1 Woche bis 10 Tage)
Reihenfolge
Framework festlegen - Vorschlag Google Firebase (Kommunikation) 
Verbindung zum Host implementieren
Hauptmenü festlegen (Startbildschirm)
Untermenü (Spiel beitreten, Optionen...)
Spielbrett, Aufbau (Klassisch oder eigene Version?) 
Würfeln (Sensoren einbauen, Handy schütteln zum Würfeln)
Regeln für's Würfeln festlegen
Ereigniskarten abbilden (wie sollen sie aussehen, bzw. welche Aufgaben enthalten Sie)
Bänker festlegen (Austeilen des Startguthabens, generelles Abwickeln der Geldgeschäfte)
Auslösen der einzelnen Karten
Kauf von Karten - (Auktionsfunktion)
Karten tauschen
Ist es möglich mitten im Spiel einzusteigen?
Schummelfunktion: Beispiel das man nur auf Felder von einem selber kommt, nicht auf die von seinem Gegner. (jedoch aufdecken?) 
Geldregen (ev. durch Sensoren, wenn man Handy schüttelt dann bekommt man unterschiedliche Beträge ausgezahlt)
