### ISSUE TITLE
Create app screens and navigation

### ISSUE THREAD

**Issue by bferijan** [SS20-SE2-Monopoly-Team/monopoly#10]
**Describe the solution you'd like**
When the user starts the app he sould get a menu to host games, join games and to change his options. (like username)

**Comment by valentingavran** [comment]
I would recommend using the new Android Navigation component. See this link for getting started: https://developer.android.com/guide/navigation/navigation-getting-started

We will only have one Activity (MainActivity) and every other View should be a Fragment.
