### ISSUE TITLE
Define network communication data

### ISSUE THREAD

**Issue by bferijan** [SS20-SE2-Monopoly-Team/monopoly#14]
**Describe the solution you'd like**
After a new game started, the host should create an initial game state. This game state includes money of players, player position and all other relevant information. When a user makes a move (rolles the dices, or cheats) he should send a message to the host. The host recalculate the gamestate and send it to the client's who repaint the gameboard.

**Comment by valentingavran** [comment]
The game and all preferences should be initialized in the respective activities and fragments and therefore this does not fit this issue, which is supposed to be based on the network level. Sending and receiving was also already implemented in Issue #9 .

Therefore, this issue will focus on the skeleton of the event methods and server-response-notifiers, which will be accessed later by the UI. All other methods should be added to each game feature (event for moving, event for buying, ...) one by one during development, as it is impossible to plan everything now.
