### ISSUE TITLE
Create the client-server communication and the corresponding classes

### ISSUE THREAD

**Issue by bferijan** [SS20-SE2-Monopoly-Team/monopoly#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

At the network level, a server should be started on an available port when the user creates a new lobby. The server should be able to receive messages from multiple clients (maximum and minimum number of clients depends on the official Monopoly game rules).

Players who want to join a game (clients) should be able to connect to the server and send messages to it. 

The IP address and the port are both provided by a superior layer

**Additional context**

**Comment by valentingavran** [comment]
A server can be started from any smartphone at any time. Whether other players connect to this server (join the lobby) is not up to the app.

**Comment by valentingavran** [comment]
Not yet finished. Review still in progress. Closes automatically with the merge.
